dbs:
- db_name: "rel-avito"
  task_name: 
  - "user-visits"
  - "user-clicks"
  - "ad-ctr"
- db_name: "rel-event"
  task_name: 
  - "user-repeat"
  - "user-ignore"
  - "user-attendance"
- db_name: "rel-f1"
  task_name:
  - "driver-top3"
  - "driver-dnf"
  - "driver-position"
  - "driver-wins"
  - "constructor-scores-points"
  - "driver-position-change"
- db_name: "rel-avs"
  task_name: 
  - "repeater"
- db_name: "rel-ieeecis"
  task_name:
  - "transaction-fraud"
- db_name: "rel-hm"
  task_name: 
  - "user-churn"
  - "item-sales"
  - "customer-spending"
  - "customer-average-price"
- db_name: "rel-stack"
  task_name: 
  - "user-engagement"
  - "user-badge"
  - "post-votes"
  - "user-comment-count"
- db_name: "rel-trial"
  task_name: 
  - "study-adverse"
  - "site-success"
  - "study-outcome"


