model_type: rdl
encoder_num_layers: 4
channels: 64
torch_frame_model_cls: resnet
batch_size: 128
eval_batch_size: 256
num_negative_samples: 1
share_same_time: true
gnn_config:
  pre_sf: src_dst
  post_sf: none
  hidden_channels: 64
  num_heads: 1
  dropout: 0.0
  norm: layernorm
  aggregation: sum
  jk: false
  skip_connection: false
  mpnn_type: pna
  mpnn_design_choice: sage
  loss_fn: bce
sampler_config:
  temporal: uniform
  num_neighbors: 64
  num_layers: 4
  loader_type: node
optimizer_config:
  lr: 0.001
  weight_decay: 0.0
  scheduler: exponential
  gamma: 0.8
