model_type: fs
dfs_layer: 2
torch_frame_model_cls: lightgbm
batch_size: 64
eval_batch_size: 128
negative_sampling_ratio: 5
auto_config:
  sample_num: 50000
  num_trials: 1
  temporal: 'delete_both'
optimizer_config:
  lr: 0.001
  weight_decay: 1.0e-05
  scheduler: expontential
  gamma: 0.8
