model_type: rdl
encoder_num_layers: 4
channels: 16
torch_frame_model_cls: resnet
batch_size: 32
eval_batch_size: 256
num_negative_samples: 1
share_same_time: true
zero_init: false
no_time: true
gnn_config:
  pre_sf: none
  post_sf: identity
  hidden_channels: 16
  num_heads: 1
  dropout: 0.0
  norm: layernorm
  aggregation: sum
  jk: false
  skip_connection: false
  mpnn_type: sage
  mpnn_design_choice: sage
  loss_fn: bce
sampler_config:
  temporal: last
  num_neighbors: 128
  num_layers: 1
  loader_type: node
optimizer_config:
  lr: 0.0038
  weight_decay: 0
  scheduler: expontential
  gamma: 0.906
